### ISSUE TITLE
Can't build repo

### ISSUE THREAD

**Issue by moxious** [EdgarLopezPhD/PaySim#1]
This repository seems to reference missing classes, without dependency information.

Also, is there a relationship between this code and BankSim?   Would appreciate any help on how to get this software built and working.

**Comment by EdgarLopezPhD** [comment]
you need to download and attach the MASON classes from the JAR found here: https://cs.gmu.edu/~eclab/projects/mason/
Both BankSim and PaySim have similarities, however BankSim was made for a different project and uses different data as input, for more information please read the bankSim papers http://folk.ntnu.no/edgaralo/wp/publications/?tgid=176&yr=&type=&usr=1&auth=#tppubs
