### ISSUE TITLE
Not being able to run PaySim

### ISSUE THREAD

**Issue by AxelRocha** [EdgarLopezPhD/PaySim#10]
I'm having the same issue as #1 . I tried to solve the problem by downloading the MASON classes and attaching it. But still, I don't know for sure if I'm compiling the project correctly. I even tried to solve some dependencies problems and still got some packages missing. 

Is there any way to publish a list of all the packages needed to run the project, or even a step by step instruction on how to run the project ?

Thanks.

**Comment by gadcam** [comment]
Hello @AxelRocha,

Some time after #1 was closed Maven build system was put in place. The [pom.xml](https://github.com/EdgarLopezPhD/PaySim/blob/master/pom.xml) file is telling to the IDE how to build the project.
If you import the project in your IDE as a Maven project you should be able to run it in one click just after cloning the repository.

**Comment by AxelRocha** [comment]
Hello @gadcam,

So, I installed Intellij and imported the PaySim project. I managed to build it but I can't find a way to run it. When I go over Run -> Edit Configurations, I select Maven and I don't know what I should use as command line. Can you help me? (I'm not being able to run it)

**Comment by gadcam** [comment]
Hello @AxelRocha,

I think either you can find a green arrow in the IntelliJ interface (at the top) to run it, or you can go to the build folder, open a command line here and run <code>java -jar paysim.jar</code>.

I close this issue as it does not seems anymore to be a problem related to PaySim but feel free to reply if you feel I can help you out.

**Comment by AxelRocha** [comment]
Hello @gadcam ,

The green arrow is inactive. So I tried building first, builds succesfully but I green arrow still inactive. The other problem is, there's no .jar files on PaySim repo.
Even after building it.

**Comment by gadcam** [comment]
Hello @AxelRocha,
You are right there is no jar file. I now installed IntelliJ to test my solution so this should work :)
To make the arrow active you just need to go to the main class which is org.paysim.paysim.PaySim. And when you open this file IntelliJ will build.
(The file is in src\main\java\org\paysim\paysim).
