### ISSUE TITLE
Can't manage to run PaySim

### ISSUE THREAD

**Issue by gustavohornig** [EdgarLopezPhD/PaySim#11]
Hey guys, I'm having the same issue as #10 , I'm using IntelliJ to run PaySim. So I imported the project using Maven module. After that, I tried to build and IntelliJ did it succesfully. The problem arrives:
In issue #10 you said to "use the green arrow or run java -jar paysim.jar" but I can't manage to do both.

![Captura de tela de 2019-04-29 10-43-58](https://user-images.githubusercontent.com/43782164/56900243-b9a2a600-6a6b-11e9-94a5-4207c0ec3de0.png)

As you can see in the screenshot, I can't run using the green arrow. Plus, there isn't a file named paysim.jar even after building it. 

Can you help me figure it out? 

Thanks

**Comment by gadcam** [comment]
Hello @gustavohornig,
See new comment on #10 : 

> To make the arrow active you just need to go to the main class which is org.paysim.paysim.PaySim. And when you open this file IntelliJ will build.
> (The file is in src\main\java\org\paysim\paysim).
