### ISSUE TITLE
Fraud cases too easy to detect

### ISSUE THREAD

**Issue by pablogf75** [EdgarLopezPhD/PaySim#13]
I have simulated two new groups of datasets with the next configuration in the file PaySim.properties:
seed=981424524
nbSteps=720
multiplier=1.0
nbFraudsters=1000
nbMerchants=34749
fraudProbability=0.001
transferLimit=2.0E10
transactionsTypes=./paramFiles/transactionsTypes.csv
aggregatedTransactions=./paramFiles/aggregatedTransactions.csv
clientsProfilesFile=./paramFiles/clientsProfiles.csv
initialBalancesDistribution=./paramFiles/initialBalancesDistribution.csv
maxOccurrencesPerClient=./paramFiles/maxOccurrencesPerClient.csv
outputPath=./outputs/
saveToDB=false
dbUrl=jdbc:mysql://localhost:3306/paysim
dbUser=none
dbPassword=none

And the other:
seed=1013659566
nbSteps=720
multiplier=1.0
nbFraudsters=1000
nbMerchants=34749
fraudProbability=3.0E-4
transferLimit=200000.0
transactionsTypes=./paramFiles/transactionsTypes.csv
aggregatedTransactions=./paramFiles/aggregatedTransactions.csv
clientsProfilesFile=./paramFiles/clientsProfiles.csv
initialBalancesDistribution=./paramFiles/initialBalancesDistribution.csv
maxOccurrencesPerClient=./paramFiles/maxOccurrencesPerClient.csv
outputPath=./outputs/
saveToDB=false
dbUrl=jdbc:mysql://localhost:3306/paysim
dbUser=none
dbPassword=none

In both cases, the fraud cases are very easy to detect with rules.
E.g. with the two first characters of nameOrig and nameDest, related with oldBalanceDest, we find 1003 of 1007 cases. Also if you grab the subset of isFraud==1, and look at it, the overwhelming majority of cases appear as a TRANSFER followed immediately by a CASHOUT of the same amount. Looking at the isFraud==0 data, the same scenario does not exist. Therefore, a simple scoring algorithm, not even involving a model, would just keep track of pairs of rows with a rule like: IF row.type=="CASHOUT" and row.amount = [row-1].amount THEN [row-1].isFraud=true and row.isFraud=true. 
Is it possible that any property or param file  could fix this?

**Comment by gadcam** [comment]
Hi @pablogf75,

First I am happy to see you are interested in the simulator!

>In both cases, the fraud cases are very easy to detect with rules.
E.g. with the two first characters of nameOrig and nameDest, related with oldBalanceDest, we find 1003 of 1007 cases.

In this case, you are using an artefact in the data : <code>the two first characters of nameOrig and nameDest</code> is not a feature you can use in the real word as beside the first letter, which is an identifier of the type of agent, the rest of this identifier is meaningless. So there could be a flaw in how this, supposed to be, random identifier is generated. But it is not a real problem as the identifier could never be used as a feature.
In a real system, you can sometime use the identifier of a client to derive another feature, like where the account was created, or at what date. But here, there must be no meaningful correlation like this.

> Therefore, a simple scoring algorithm, not even involving a model, would just keep track of pairs of rows with a rule like: IF row.type=="CASHOUT" and row.amount = [row-1].amount THEN [row-1].isFraud=true and row.isFraud=true.

First the isFraud field is what you are looking to predict (your Y) so you can not use it as a feature.

You are also using an artefact of the data here: you can not use the "ID of the transaction" as a feature without deriving a meaningful feature of it.


If you want to read how the fraudster are implemented you can browse the following folder : https://github.com/EdgarLopezPhD/PaySim/tree/master/src/main/java/org/paysim/paysim/actors
