### ISSUE TITLE
New simulations get frozen

### ISSUE THREAD

**Issue by dasirra** [EdgarLopezPhD/PaySim#4]
I'm trying to generate new fraud datasets but i'm having troubles. My problem is that that simulation stops between steps 199 and 299. It seems that it's running but I cannot see any progress after several hours running. Here is the console output:
![image](https://user-images.githubusercontent.com/6038446/48983384-a2dbda00-f0ee-11e8-985a-e99a17ea98bf.png)

And here is my configuration file.
```
#PaySim parameters
seed=time
nbSteps=719
multiplier=1
nbFraudsters=1000
nbMerchants=30000
nbBanks=5
fraudProbability=0.0003
transferLimit=200000
aggregateTransactionsParams=./paramFiles/AggregateTransaction.csv
transferMaxPath=./paramFiles/transferMax.csv
balanceHandler=./paramFiles/initialBalanceClients.csv
transferFreqMod=./paramFiles/transferFreq4Mod.csv
transferFreqModInit=./paramFiles/transferFreq4ModInit.csv
outputPath=./outputs/
saveToDB=0
dbUrl=jdbc:mysql://localhost:3306/paysim
dbUser=none
dbPassword=none
```

All help is welcome. Thank you in advance

**Comment by gadcam** [comment]
Hello @dasirra,
I also encounter this bug sometimes.
I am currently rewriting part of the simulation mechanism so I will not investigate deeper before the rewrite is finished. I hope it will solve this problem as a side-effect.

A workaround which works for me is just restarting PaySim and the second time it is working for me.

**Comment by gadcam** [comment]
Hello @dasirra,
#6 fix this bug.
Feel free to reopen this bug if you still experience it.
