### ISSUE TITLE
Zero-balance transactions

### ISSUE THREAD

**Issue by dasirra** [EdgarLopezPhD/PaySim#5]
There are many cases in which a client can perform transactions without enough money in their balance. Does it have any special meaning?

**Comment by gadcam** [comment]
Hello @dasirra 
There is currently no management of overdrafts.
Said another way: the current management of overdraft is to let the transaction occur and set the balance to zero.

The code responsible of this is available here
https://github.com/EdgarLopezPhD/PaySim/blob/988d83fd2874a5ff5b1e81eb89181cc6b3c33281/src/paysim/actors/SuperActor.java#L37-L43

I am working on this question however there is no simple solution : it is desirable to have overdrafts in the generated data however we should not let it grow to much.
How do we set a limit for a given client ? In a realistic setup we should set different threshold for different client profiles.

**Comment by gadcam** [comment]
Hello @dasirra,
A basic overdraft management system was added in 79105cd695cabe5b9c1f81e172cf5c7501277661.
